import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SWRProviders from "./swr-provider";
import { Header } from "@/components/header";
import localFont from "next/font/local";
import { Footer } from "@/components/footer";
// import Script from "next/script";

const LPMQ = localFont({
  src: "../font/LPMQ.ttf",
  display: "swap",
  variable: "--font-LPMQ",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${LPMQ.variable} bg-zinc-100`}>
        <SWRProviders>
          <Header />
          <main className="relative mx-auto min-h-[calc(100vh-var(--header-height)-var(--footer-height))] max-w-screen-xl px-6 min-[435px]:px-12">
            {children}
          </main>
          <Footer />
        </SWRProviders>
      </body>
      {/* <Script async src="https://www.tiktok.com/embed.js" /> */}
    </html>
  );
}
